<!DOCTYPE html>

<html ng-app="exampleApp">
<head>
    <title>$exceptionHandler</title>

    <script src="../Libraries/angular.js"></script>
    <link href="../Libraries/bootstrap-theme.css" rel="stylesheet" />
    <link href="../Libraries/bootstrap.css" rel="stylesheet" />

    <script>
        angular.module("exampleApp", [])
        .controller("defaultCtrl", function ($scope, $exceptionHandler) {

            // Все не обработанные исключения (не отловленные в конструкции try catch) предаются сервису $exceptionHandler
            // и отображаються в консоли с помощью console.error()

            //$scope.throwEx = function () {
            //    throw new Error("Triggered Exception");
            //}

            // Для того, чтобы предоставить больше данных о исключении, можно использовать сервис напрямую
            $scope.throwEx = function () {
                try {
                    throw new Error("Triggered Exception");
                } catch (ex) {
                    $exceptionHandler(ex.message, "Button Click");
                }
            }
        });
    </script>
</head>
<body ng-controller="defaultCtrl">
    <div class="panel panel-default">
        <div class="panel-body">
            <button class="btn btn-primary" ng-click="throwEx()">
                Throw Exception
            </button>
        </div>
    </div>
</body>
</html>
